name: DEI badging application for projects
description:  Please use the following to apply for the CHAOSS DEI Project Badge.
title: "[Project-Application] "
labels: ["initial-submission"]
assignees:
  - Badger Bot 🦡
  
body:
  - type: markdown
    attributes:
      value: "# Open Source Project Submission"
  - type: markdown
    attributes:
      value: "## Please Fill in the Following Fields"

  - type: input
    id: ProjectLink
    attributes:
      label: Link to the project's repository or website
      description: "Enter the link of the project repository or website"
    validations:
      required: true

  - type: dropdown
    id: DocsPublic
    attributes:
      label: Is your project documentation publically available?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true

  - type: dropdown
    id: ContentsPublic
    attributes:
      label: Are your project contents in a repository that is publicly available?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true


