name: DEI badging application for projects
description:  Please use the following to apply for the CHAOSS DEI Project Badge.
title: "[Project-Application] "
labels: ["initial-submission"]
assignees:
  - Badger Bot 🦡
  
body:
  - type: markdown
    attributes:
      value: "# Open Source Project Submission"
  - type: markdown
    attributes:
      value: "## Please Fill in the Following Fields"

  - type: input
    id: ProjectLink
    attributes:
      label: Link to the project's repository or website
      description: "Enter the link of the project repository or website"
    validations:
      required: true

  - type: dropdown
    id: DocsPublic
    attributes:
      label: Is your project documentation publically available?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true

  - type: dropdown
    id: ContentsPublic
    attributes:
      label: Are your project contents in a repository that is publicly available?
      options:
        - 'yes'
        - 'no'
    validations:
      required: true

  - type: markdown
    attributes:
      value: "<br />"

  - type: markdown
    attributes:
      value: "### Provide a links to the following files in your project's repository:"

  - type: input
    id: DEImdLink
    attributes:
      label: DEI.md Link
      description: A DEI.md file is a new and special file associated with CHAOSS DEI Project Badging. The publically available file must be placed in a community-level repository (i.e., .github or community repositories) or on your website. The DEI.md contains descriptions of how you attend to specific CHAOSS DEI-related metrics. A template is available at [DEI.md Template](https://github.com/badging/project-diversity-and-inclusion/blob/master/resources/diversity-equity-inclusion.md)
    validations:
      required: true
